name: fractalviewer
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html_core: ^0.10.3

  provider: ^6.0.5
  http: ^0.13.5
  intl:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/attractorshader.frag
    - shaders/customfractalshader.frag
  #uses-material-design: true

  generate: true