{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float zoom;\nuniform vec2 uPos;\nuniform vec2 mousePos;\nuniform float brotOrJulia;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec3 FLT_flutter_local_hsv2rgb(vec3 c)\n{\n    vec4 K = vec4(1.0, 0.666666686534881591796875, 0.3333333432674407958984375, 3.0);\n    vec3 p = abs((fract(c.xxx + K.xyz) * 6.0) - K.www);\n    return mix(K.xxx, clamp(p - K.xxx, vec3(0.0), vec3(1.0)), vec3(c.y)) * c.z;\n}\n\nvec4 FLT_flutter_local_colorFor(int i, float length)\n{\n    float iteration = float(i) - (1.4375 * log(log(length) / 0.693147182464599609375));\n    vec3 param = vec3(iteration / 20.0, 1.0, 1.0);\n    vec3 rgb = FLT_flutter_local_hsv2rgb(param);\n    return vec4(rgb, 1.0);\n}\n\nvec2 FLT_flutter_local_squareImaginary(vec2 number)\n{\n    return vec2((number.x * number.x) - (number.y * number.y), (2.0 * number.x) * number.y);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 z0 = uPos + (((fragCoord * 2.0) - uSize) / vec2(min(uSize.x, uSize.y) * zoom));\n    vec2 uv = z0;\n    if (brotOrJulia > 0.0)\n    {\n        uv = mousePos;\n    }\n    fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n    for (int i = 0; i < 942; i++)\n    {\n        if (length(z0) > 256.0)\n        {\n            int param = i;\n            float param_1 = length(z0);\n            fragColor = FLT_flutter_local_colorFor(param, param_1);\n            break;\n        }\n        vec2 param_2 = z0;\n        z0 = FLT_flutter_local_squareImaginary(param_2) + uv;\n    }\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "uSize",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "zoom",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "uPos",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 3,
      "name": "mousePos",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 4,
      "name": "brotOrJulia",
      "rows": 1,
      "type": 10
    }
  ]
}